--
--   opcoes
--       -- teclas escala cromatica
--       -- teclas escala diatonica
-- + aumentar a escala
-- - diminuir a escala
-- N mostrar quadro de notas
-- I mostrar tela de instrumentos musicais
-- A mostrar tela de instrumentos percussão um/vez 
-- B escala baixos
-- ESCALA = exibe a escala atual
--
-- - + N I A B ESCALA
-- 
-- Cb
-- G# B  C# E  G# B  D#
-- F# A# D# F# A# C# E
-- 
-- Gb
-- F  G# B  D# F# A# 
-- F# A# C# F  G# B
-- 
-- Db
-- C  D# F# A# C# F
-- C# F  G# C  D# F#
-- 
-- Ab
-- G  A# C# F  G# C 
-- G# C  D# G  A# C#
-- 
-- Eb
-- D  F  G# C  D# G 
-- D# G  A# D  F  G#
-- 
-- Bb
-- G  C  D# G  A# D 
-- A# D  F  A  C  D#
-- 
-- F
-- E  G  A# D  F  A
-- F  A  C  E  G  A#
--
-- C
-- G  B  D  F  A  C  E
-- A  C  E  G  B  D  F
-- 
-- F# A  C  E  G  B
-- G  B  D  F# A  C
-- 
-- C# E  G  B  D  F#
-- D  F# A  C# E  G
-- 
-- G# B  D  F# A  C#
-- A  C# E  G# B  D
-- 
-- D# F# A  C# E  G#
-- E  G# B  D# F# A
-- 
-- A# C# E  G# B  D#
-- B  D# F# A# C# E
